version: 2
sources:
  - name: dwh
    database: gh-archive-345218
    schema: gh_archive_all
    tables:
      - name: gh_external_table
        location: 'gs://data_lake_gh-archive-345218/raw/*'
        options:
          format: parquet
          hive_partition_uri_prefix: 'gs://bucket/path/'

models:
  - name: dwh_days
    description: >
      GitHub activity partitioned by days.